AbsaOSS/cobrix

cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/CopybookParser.scala
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/common/ReservedWords.scala

Addresses #34.
Do you want me to add a unit-test for this case?

Allow field names to start with COMP-

---

cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/CopybookParser.scala

Interpret Decimal values with no fractional digits as Integral

---

README.md

Minor modifications for file, spelling and grammar

Correct spelling and grammar

---

README.md
cobol-parser/pom.xml
examples/spark-cobol-app/pom.xml
examples/spark-codec-app/pom.xml
examples/spark-type-variety/pom.xml
pom.xml
spark-cobol/pom.xml

Fixed minor issues for Enceladus integration

Release Cobrix 0.5.3

---

cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/ParserVisitor.scala

Fixed a bug on OCCURS ... TO ... clauses.

---

README.md

#127 Add a badge for the master branch build.

---

cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/Copybook.scala
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/CopybookParser.scala

Remove the MutableCopybook type.

---

README.md
cobol-parser/pom.xml
data/test19_display_num.cob
examples/spark-cobol-app/pom.xml
pom.xml
spark-cobol/pom.xml

It should be the last release via Maven.
Go sbt!

Release 1.1.2

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

Because of the rise of popularity of this repo I think this could help the users.

Add issue templates for GitHub

---

cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/ParserJson.scala
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/json.g4
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/jsonBaseVisitor.java
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/jsonLexer.java
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/jsonParser.java
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/jsonVisitor.java
cobol-parser/src/test/scala/za/co/absa/cobrix/cobol/parser/parse/JsonSpec.scala
project/Dependencies.scala
spark-cobol/pom.xml
spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/parameters/CobolParametersParser.scala
spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/integration/Test25OccursMappings.scala

Custom JSON parser following the discussion on #283

Json parser

---

cobol-converters/pom.xml
cobol-parser/pom.xml
pom.xml
project/Dependencies.scala
spark-cobol/pom.xml
version.sbt

Updated minor version of Cobrix artifacts since project dependencies have changed.

#294 Update Spark dependencies to mitigate security warnings.

---

README.md
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/FixedLenNestedReader.scala
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/Reader.scala
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/VarLenNestedReader.scala
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/iterator/FixedLenNestedRowIterator.scala
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/parameters/CobolParameters.scala
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/parameters/ReaderParameters.scala
spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/parameters/CobolParametersParser.scala
spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/DefaultSource.scala
spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/scanners/CobolScanners.scala
spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/CobolRelationSpec.scala
spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/base/impl/DummyFixedLenReader.scala
spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/integration/Test27RecordLengthSpec.scala

Add support for specifying record length when reading fixed-record length files.

---

build.sbt
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/FixedLenNestedReader.scala
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/FixedLenReader.scala
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/VarLenNestedReader.scala
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/VarLenReader.scala
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/iterator/VarLenHierarchicalIterator.scala
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/iterator/VarLenNestedIterator.scala
spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/reader/VarLenNestedReader.scala

Improve assembly to make better uber jars

---

cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/Copybook.scala
cobol-parser/src/test/scala/za/co/absa/cobrix/cobol/parser/copybooks/CopybookRequirementsSpec.scala

#386 Add a better error message when handling copybooks with non-GROUP root fields

---

cobol-parser/src/test/scala/za/co/absa/cobrix/cobol/parser/parse/SyntaxErrorsSpec.scala

- added missing name into unit test
Closes #537

#537 - found unit test with empty name

---

README.md
cobol-parser/pom.xml
project/Dependencies.scala

trying to upgrade antlr version to 4.8 to address issue described in #561

upgrade antlr version to 4.8

---

README.md
cobol-converters/pom.xml
cobol-parser/pom.xml
examples/examples-collection/pom.xml
examples/spark-cobol-app/build.sbt
examples/spark-cobol-app/pom.xml
examples/spark-cobol-s3-standalone/pom.xml
examples/spark-cobol-s3/pom.xml
pom.xml
spark-cobol/pom.xml
version.sbt

* #624 Add support for binary fields by @yruslan in https://github.com/AbsaOSS/cobrix/pull/626

Release Cobrix v.2.6.8

---

README.md
cobol-converters/pom.xml
cobol-parser/pom.xml
examples/examples-collection/pom.xml
examples/spark-cobol-app/build.sbt
examples/spark-cobol-app/pom.xml
examples/spark-cobol-s3-standalone/pom.xml
examples/spark-cobol-s3/pom.xml
pom.xml
spark-cobol/pom.xml
version.sbt

* #653 dd support for new EBCDIC code pages: 273, 500, 1140, 1141, 1148 in https://github.com/AbsaOSS/cobrix/pull/654

Release v2.6.10

---

.github/workflows/build.yml
.github/workflows/fossa.yml
.github/workflows/jacoco_check.yml
.github/workflows/release.yaml
README.md
build.sbt
project/Dependencies.scala

#661 Add release via CI/CD

---

spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/utils/SparkUtils.scala
spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/utils/SparkUtilsSuite.scala

This is similar to flattening, but does not flatten arrays, and it is more efficient.
Closes #685

#685 Add methods for unstructing schemas and dataframes.

---

README.md
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/iterator/SegmentIdAccumulator.scala
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/parameters/ParameterParsingUtils.scala
cobol-parser/src/test/scala/za/co/absa/cobrix/cobol/reader/parameters/ParameterParsingUtilsSuite.scala
spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/parameters/CobolParametersParser.scala
spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/integration/Test17HierarchicalSpec.scala

#683 Add support for '_' for hierarchical key generation at leaf level.

---

cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/iterator/VRLRecordReader.scala
cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/validator/ReaderParametersValidator.scala
spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/integration/Test37RecordLengthMappingSpec.scala

Just so I won't forget to do this...

Improve error message when the record length field cannot be parsed as an integer.
