- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/CobolRelation.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/utils/FileUtils.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/utils/FileUtilsSpec.scala
Fixes file retrieval by complying with HDFS patterns (e.g. excluding files starting with '.' and '_') and supporting glob patterns.
> Fixes HDFS file retrieval

- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/reader/index/IndexGenerator.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/reader/parameters/ReaderParameters.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/reader/varlen/VarLenNestedReader.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/DefaultSource.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/utils/HDFSUtils.scala
to achieve bettr data locality
* The default partition size is now equal to the default size of HDFS filesystem block
* The split is improved to achieve better alignment between Spark partitions and HDFS
blocks.
> Improved default settings for sparse index generation

- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/Copybook.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/CopybookParser.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/ast/Group.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/common/DataExtractors.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/reader/iterator/FSRecordIterator.scala
- cobol-parser/src/test/scala/za/co/absa/cobrix/cobol/parser/decode/MalformedValuesSpec.scala
- cobol-parser/src/test/scala/za/co/absa/cobrix/cobol/parser/decode/UsageInheritanceSpec.scala
- cobol-parser/src/test/scala/za/co/absa/cobrix/cobol/parser/extract/BinaryExtractorSpec.scala
- cobol-parser/src/test/scala/za/co/absa/cobrix/cobol/parser/parse/FieldSizeSpec.scala
- cobol-parser/src/test/scala/za/co/absa/cobrix/cobol/parser/parse/SegmentRedefinesSpec.scala
- cobol-parser/src/test/scala/za/co/absa/cobrix/cobol/parser/parse/SyntaxErrorsSpec.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/reader/fixedlen/iterator/FixedLenFlatRowIterator.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/reader/fixedlen/iterator/FixedLenMapIterator.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/reader/fixedlen/iterator/FixedLenNestedRowIterator.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/schema/CobolSchema.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/utils/RowExtractors.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/base/impl/DummyCobolSchema.scala
This PR solves the issue with top level redefines being counted as items with own size. Solves #72.
> Allow for top level Redefines.

- README.md
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/CobolRelation.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/DefaultSource.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/parameters/CobolParameters.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/parameters/CobolParametersParser.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/scanners/CobolScanners.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/CobolRelationSpec.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/integration/Test1FixedLengthRecordsSpec.scala
This is useful for debugging copybooks for fixed length records and making them mathc a data file.
> #104 Add an option to suppress file size check

- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/reader/index/IndexGenerator.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/reader/varlen/VarLenNestedReader.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/reader/varlen/iterator/SegmentIdAccumulator.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/reader/varlen/iterator/VarLenNestedIterator.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/integration/Test5MultisegmentSpec.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/regression/Test02SparseIndexGenerator.scala
* Hierarchical indexing is only used when level ids need to be generated
* Do not rely on segments having the same segment id should also have same size
* If the data IS hierarchical do not allow any record to be generated before
any root segment is encountered. This is related to a scenario when
file headers have the same segment id as root segments
> #135 Fix partitioning issues

- README.md
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/CopybookParser.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/parameters/CobolParameters.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/parameters/CobolParametersParser.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/reader/FixedLenTextReader.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/CobolRelation.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/DefaultSource.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/scanners/CobolScanners.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/text/Test01AsciiTextFiles.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/text/Test02TextFilesOldSchool.scala
> #295 Simplify loading ASCII text files

- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/encoding/codepage/CodePage.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/encoding/codepage/CodePage875.scala
Replicated the codepage option functionality to support the 875 (EBCDIC) codepage for the Greek language.
If somehting is off feel free to contact us...
> Added support for codepage 875 (Greek)

- LICENSE
- build.sbt
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/copybookLexer.java
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/copybookParser.java
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/copybookParserBaseVisitor.java
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/copybookParserVisitor.java
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/jsonBaseVisitor.java
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/jsonLexer.java
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/jsonParser.java
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/jsonVisitor.java
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/FixedLenReader.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/Reader.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/extractors/record/RecordHandler.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/utils/HDFSUtils.scala
Also, mention 2 methods licensed via BSD bundled with the Cobol parser.
> Automatically generate license headers

- README.md
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/parameters/CobolParameters.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/parameters/CobolParametersParser.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/CobolRelation.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/DefaultSource.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/parameters/CobolParametersValidator.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/scanners/CobolScanners.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/CobolRelationSpec.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/integration/Test28MultipartLoadSpec.scala
> Add an ability to specify multiple paths to load data from

- README.md
- cobol-converters/pom.xml
- cobol-parser/pom.xml
- cobol-parser/src/test/scala/za/co/absa/cobrix/cobol/reader/extractors/raw/RawRecordContextFactory.scala
- examples/examples-collection/pom.xml
- examples/spark-cobol-app/build.sbt
- examples/spark-cobol-app/pom.xml
- examples/spark-cobol-s3-standalone/pom.xml
- examples/spark-cobol-s3/pom.xml
- pom.xml
- spark-cobol/pom.xml
- version.sbt
> Release Cobrix 2.4.0

- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/decoders/StringDecoders.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/decoders/StringTools.scala
- cobol-parser/src/test/scala/za/co/absa/cobrix/cobol/parser/decoders/StringDecodersSpec.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/regression/Test15AsciiNumberOverflow.scala
Expect this to happen when a parsed test looks like scientific notation (2+e99)
> #433 Possible fix for big integer overflows.

- README.md
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/internal/Logging.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/Copybook.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/CopybookParser.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/ANTLRParser.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/antlr/ParserJson.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/decoders/BinaryUtils.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/encoding/codepage/CodePage.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/headerparsers/RecordHeaderParserFactory.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/VarLenNestedReader.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/index/IndexGenerator.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/iterator/FixedLenNestedRowIterator.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/iterator/VRLRecordReader.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/schema/CobolSchema.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/parameters/CobolParametersParser.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/schema/CobolSchema.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/CobolRelation.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/DefaultSource.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/index/IndexBuilder.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/scanners/CobolScanners.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/utils/FileUtils.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/utils/SparkUtils.scala
https://github.com/AbsaOSS/cobrix/issues/477
Make all loggers `@transient` for compatibility with non-default logger implementations
> #477 Fixed NotSerializableException when using non-default logger implementations

- README.md
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/iterator/FixedLenNestedRowIterator.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/parameters/CobolParametersParser.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/scanners/CobolScanners.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/regression/Test13AsciiCrLfText.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/regression/Test21VariableOccursForTextFiles.scala
Variable OCCURS resulted with null fields after the OCCURS field when record_format=D. This is now fixed.
> #553 Fix a regression bug introduced in #543 concerning variable OCCURS.

- .github/workflows/jacoco_check.yml
- build.sbt
- project/plugins.sbt
- Update of plugins file to support current Absa-JaCoCo workaround.
- New yml file for server side check.
Closes #602
> #602 - Add GitHub action for code-coverage check

- .github/workflows/jacoco_check.yml
- README.md
- cobol-converters/pom.xml
- cobol-parser/pom.xml
- examples/examples-collection/pom.xml
- examples/spark-cobol-app/build.sbt
- examples/spark-cobol-app/pom.xml
- examples/spark-cobol-s3-standalone/pom.xml
- examples/spark-cobol-s3/pom.xml
- pom.xml
- spark-cobol/pom.xml
- version.sbt
* #634 Retain metadata on schema flattening in https://github.com/AbsaOSS/cobrix/pull/635
* #644 Add support for Spark 3.5.0 in https://github.com/AbsaOSS/cobrix/pull/645
> Release Cobrix v.2.6.9

- build.sbt
- project/Dependencies.scala
- project/plugins.sbt
Closes #680
Also, the shading of dependent libraries is improved for 'sbt assembly'.
> #680 Shade ANTLR for cobol-parser so that it won't clash with Spark's ANTLR runtime.

- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/utils/SparkUtils.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/utils/SparkUtilsSuite.scala
> #697 Improve metadata merging method in Spark Utils.

- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/VarLenNestedReader.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/extractors/raw/FixedWithRecordLengthExprRawRecordExtractor.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/iterator/VRLRecordReader.scala
- cobol-parser/src/test/scala/za/co/absa/cobrix/cobol/reader/iterator/VRLRecordReaderSpec.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/integration/Test37RecordLengthMappingSpec.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/regression/Test26FixLengthWithIdGeneration.scala
> #710 Fix index generation for files with record length fields or expressions.

- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/scanners/CobolScanners.scala
Spark-cobrix connectors processing fixed-length files can encounter race conditions when used concurrently in multiple threads or multiple notebooks sharing the same Spark driver. This will lead to assertion error 
```
Py4JJavaError: An error occurred while calling o2411.saveAsTable.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 22 in stage 3238.0 failed 4 times, most recent failure: Lost task 22.3 in stage 3238.0 (TID 50850) (x.x.x.x executor 27): java.lang.AssertionError: assertion failed: Byte array does not have correct length
at scala.Predef$.assert(Predef.scala:223)
at org.apache.spark.SparkContext.$anonfun$binaryRecords$2(SparkContext.scala:1603)
at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
at …
```
> Avoid a race condition on Fixed record-length file processing. 

- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/source/scanners/CobolScanners.scala
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/utils/FileUtils.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/integration/Test27RecordLengthSpec.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/regression/Test07IgnoreHiddenFiles.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/utils/FileUtilsSpec.scala
> #719 Improve the error message about file size not divisible by record size.

- .github/workflows/jacoco_check.yml
- README.md
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/encoding/codepage/CodePage.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/encoding/codepage/CodePage1145.scala
- cobol-parser/src/test/scala/za/co/absa/cobrix/cobol/parser/decoders/StringDecodersSpec.scala
- cobol-parser/src/test/scala/za/co/absa/cobrix/cobol/parser/encoding/codepage/CodePageSingleByteSpec.scala
which is same as CP284 with € at the position of the international currency symbol ¤.
Closes #728
> #728 Add CP1145 code page (Spain and Latin America)

- README.md
- build.sbt
- cobol-parser/pom.xml
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/decoders/BinaryUtils.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/decoders/FloatingPointDecoders.scala
- pom.xml
- project/Dependencies.scala
> #258 Remove dependency on `scodec`.

- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/decoders/BinaryNumberDecoders.scala
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/parser/decoders/DecoderSelector.scala
- cobol-parser/src/test/scala/za/co/absa/cobrix/cobol/parser/decoders/BinaryDecoderSpec.scala
- data/test17_expected/test17a_schema.json
- data/test17_expected/test17b_schema.json
- data/test17_expected/test17c_schema.json
- data/test18 special_char_expected/test18a_schema.json
- data/test24_expected/test24_schema.json
- data/test24_expected/test24b_schema.json
- data/test6_expected/test6_schema.json
- spark-cobol/src/main/scala/za/co/absa/cobrix/spark/cobol/schema/CobolSchema.scala
- spark-cobol/src/test/scala/za/co/absa/cobrix/spark/cobol/source/integration/Test38StrictBinaryTypeSpec.scala
> #740 extend binary type support to make sure unsigned binary fields can fit Spark data types

- README.md
- cobol-parser/src/main/scala/za/co/absa/cobrix/cobol/reader/extractors/raw/FixedWithRecordLengthExprRawRecordExtractor.scala
- cobol-parser/src/test/scala/za/co/absa/cobrix/cobol/reader/iterator/VRLRecordReaderSpec.scala
- pom.xml
> #744 Add the ability to specify default record length for the record length field mapping
